7.4 8.0 8.1 8.2 8.3 8.4 8.5:
	docker build -t registry.hiqdev.com/hiqdev/docker-ci-images/php-nginx:$@ $@
	docker push registry.hiqdev.com/hiqdev/docker-ci-images/php-nginx:$@

.PHONY: 7.4 8.0 8.1 8.2 8.3 8.4 8.5
