name: Build

env:
  PERIODIC_UPDATES_MIN_VERSION: 8.2
  REGISTRY: ghcr.io
  PHP_IMAGE_NAME: ghcr.io/hiqdev/docker-ci-images/php-nginx
  PLAYWRIGHT_IMAGE_NAME: ghcr.io/hiqdev/docker-ci-images/playwright

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  schedule:
    - cron: 0 1 * * 0

jobs:
  generate-jobs:
    name: Generate Jobs
    runs-on: ubuntu-latest
    outputs:
      strategy: ${{ steps.generate-jobs.outputs.strategy }}
    steps:
      -
        uses: actions/checkout@v3
      -
        uses: dorny/paths-filter@v2
        if: ${{ github.event_name != 'schedule' }}
        id: changes
        with:
          list-files: json
          filters: |
            php-nginx:
              - 'php-nginx/**'
            playwright:
              - 'playwright/**'
      -
        id: generate-jobs
        name: Generate Jobs
        run: |
          strategy="$(./scripts/generate-actions.sh ${{ github.event_name }} '${{ steps.changes.outputs.version_files }}' "${PERIODIC_UPDATES_MIN_VERSION}")"
          jq . <<<"$strategy" # sanity check / debugging aid
          echo "strategy=$strategy" >> $GITHUB_OUTPUT

  build:
    needs: generate-jobs
    strategy: ${{ fromJson(needs.generate-jobs.outputs.strategy) }}
    name: build-${{ matrix.type }}-${{ matrix.version }}
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Compute Image Tag
        id: meta
        run: |
          if [ "${{ matrix.type }}" = "php-nginx" ]; then
            echo "tag=${{ env.PHP_IMAGE_NAME }}:${{ matrix.version }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ env.PLAYWRIGHT_IMAGE_NAME }}:${{ matrix.version }}" >> $GITHUB_OUTPUT
          fi

      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:${{ matrix.type }}/${{ matrix.version }}"
          tags: ${{ steps.meta.outputs.tag }}
          push: ${{ github.event_name != 'pull_request' }}
